# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=8)),
                ('stop_code', models.CharField(max_length=8)),
                ('stop_desc', models.CharField(max_length=40)),
                ('stop_name', models.CharField(max_length=40)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
