# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foo',
            old_name='min',
            new_name='departure_time',
        ),
    ]
