# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='parent_station',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stops',
            name='stop_location_type',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stops',
            name='stop_url',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stops',
            name='stop_zone',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stops',
            name='timezone',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stops',
            name='wheelchair',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_desc',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_name',
            field=models.CharField(max_length=80),
        ),
    ]
