# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160509_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_code',
            field=models.CharField(max_length=16),
        ),
    ]
