# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160509_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='parent_station',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_location_type',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_url',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_zone',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='timezone',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='wheelchair',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
