# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=8)),
                ('arrival_time', models.CharField(max_length=8)),
                ('departure_time', models.CharField(max_length=8)),
                ('stop_id', models.CharField(max_length=8)),
                ('stop_sequence', models.CharField(max_length=8)),
                ('stop_headsign', models.CharField(max_length=8)),
                ('pickup_type', models.CharField(max_length=8)),
                ('drop_off_type', models.CharField(max_length=8)),
                ('shape_dist_traveled', models.CharField(max_length=8)),
                ('timepoint', models.CharField(max_length=8)),
            ],
        ),
    ]
