# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stoptimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptimes',
            name='drop_off_type',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='pickup_type',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='shape_dist_traveled',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stoptimes',
            name='timepoint',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
