# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160509_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=8)),
                ('service_id', models.CharField(max_length=24)),
                ('trip_id', models.CharField(max_length=8)),
                ('trip_headsign', models.CharField(max_length=80)),
                ('trip_short_name', models.CharField(max_length=8, null=True)),
                ('direction_id', models.CharField(max_length=8)),
                ('block_id', models.CharField(max_length=8, null=True)),
                ('shape_id', models.CharField(max_length=8)),
                ('wheelchair_accessible', models.CharField(max_length=8)),
                ('bikes_allowed', models.CharField(max_length=8)),
            ],
        ),
    ]
