# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160512_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='route_id',
            field=models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.CASCADE, to='api.Routes'),
        ),
    ]
