# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160512_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_short_name', models.CharField(max_length=8)),
                ('trip_headsign', models.CharField(max_length=80)),
                ('min', models.CharField(max_length=8)),
            ],
        ),
    ]
